### ISSUE TITLE
Pre release appears to distribute binaries without sources

### ISSUE THREAD

**Issue by ecm-pushbx** [640-KB/GLaTICK#1]
The repo itself and the "source code" archives on https://github.com/640-KB/GLaTICK/releases/tag/v0.8.0a1 appear to only contain a readme and a license file. I don't see sources anywhere. This is not prohibited if you hold all relevant copyrights but I'd say it is against the spirit of the GPL's copyleft.

**Comment by 640-KB** [comment]
Hello,

This is only a first step in this brand new project and all code contained is 100% original and part of this project.  I believe it's just that the "source" archive is created when the tag is created and becomes a snapshot of the repo at that moment.  These ROMs are purely pre-release testing binaries where we can link early adopters to test specific use cases. The source will be posted of course once a few more pre-release bugs can be worked out and a few more internal milestones are hit. 

Sound reasonable?  Source will be posted in the near future.

**Comment by ecm-pushbx** [comment]
Big fan of release early, release often. Though I also tend to test and fix bugs before I create a changeset so I'm not that far from your choices. Just wanted to leave a note here.

**Comment by 640-KB** [comment]
Got it - and I do appreciate the note and comment!  I just figured it would be a convenient way to make authentic testing images available to those who have expressed interest in trying alpha-quality releases.  This release will eventually be replaced and deleted as the project moves closer to being ready.

**Comment by ecm-pushbx** [comment]
Hmm, not saying you should keep the release as such but it may be useful if the current state of things is preserved in some way, eg in the source history. Could be, say, a bugfix you do later actually has a disadvantage to it, so I'm all for preserving the history.

**Comment by 640-KB** [comment]
Got ya.  I do keep the developmental source versioned in a private repo, so I do have access to that as needed.  It's just still in that place where it's not quite ready to "see the light of day" so to speak, but is getting very close.  Once it gets to at least that point I will be putting up the full source and maintaining it there (even before it's "perfect" :) ).

Thanks again for the thoughts - will take it to heart!

**Comment by 640-KB** [comment]
> Hmm, not saying you should keep the release as such but it may be useful if the current state of things is preserved in some way, eg in the source history. Could be, say, a bugfix you do later actually has a disadvantage to it, so I'm all for preserving the history.

@ecm-pushbx The source for the current state of the project is now posted.
